[build]
  command = "bun run build"
  publish = ".next"

[plugins]
  [[plugins]]
    package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

[[edge_functions]]
  function = "middleware"
  path = "/*"

